function [thval Vm waveform tarr]=tms_head(a,len,rl,VL,L,Jdc,rv,phead,t2phead,epseff,dt,dur,M)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% A Boundary Element Method of Bidomain Modeling for Predicting Cellular
%                 Responses to Electromagnetic Fields
%
%             Code Author: David M. Czerwonky
%
% Description: This script runs the hybrid cable approach for TMS of an
% axon in an extracellular bath.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

addpath('./BEM_MEX_Fortran_code')
addpath('./channeldynamics/')
addpath('./Cableequation/')

%initalize the time scale
tarr=0:dt:dur;
N=numel(tarr);

%initalize the device waveform
waveform=@(t) VL(3000,t-.0002)/L.*(t-.0002>0);

%define the locations of the neuron compartments
p=zeros([M 3]);
p(:,3)=-len/2:len/(M-1):len/2;
p=p(:,[1 3 2]);
p(:,3)=p(:,3)+.07;
dl=p(2:end,:)-p(1:end-1,:);
peval=(p(2:end,:)+p(1:end-1,:))/2;

%calculate the total E-field generated by the coil
[Efield]=adjointBEM_TMS(t2phead,phead,epseff,rv,Jdc,peval');

%calculate the extracellular potentials Ve
Ve=zeros([M 1]);
Ve(1)=0;
Ve(2:end)=cumsum(sum(dl'.*Efield,1));


%define helper functions for findthreshold
getRow = @(data, rowNum) data(rowNum,1000:N);
thfunc1=@(amp) max(getRow(multicompartsolv(a,len,rl,M,-amp,Ve,waveform,dt,dur),round(M/5)))>0;

%find the actication threshold (thval) and the transmembrane voltage (Vm)
thval=findthreshold(@(amp) thfunc1(amp),10,0,.001)
Vm = multicompartsolv(a,len,rl,M,-thval,Ve,waveform,dt,dur);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                             End of Code
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%