#include <uchar.h>
int countfaces(const int nte,const  int* te2p,const int* regid,int* np);
void makeBEMmesh(const int nte,const  int* te2p,const double* p,const double* conduvals,const int* regid,int* t2p,double* pbem,double* sigdiff,double* sigav,double* rhotoIm);
int countfaceslegacy(const int nte,const  int* te2p,const double* condu,int* np);
void makeBEMmeshlegacy(const int nte,const  int* te2p,const double* p,const double* condu,int* t2p,double* pbem,double* epseff);
/* --------------------------------------------------- */
/* Automatically generated by mwrap                    */
/* --------------------------------------------------- */

/* Code generated by mwrap */
/*
  Copyright statement for mwrap:

  mwrap -- MEX file generation for MATLAB and Octave
  Copyright (c) 2007-2008 David Bindel

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You may distribute a work that contains part or all of the source code
  generated by mwrap under the terms of your choice.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

#include <mex.h>
#include <stdio.h>
#include <string.h>


#ifndef ulong
#  define ulong unsigned long
#endif
#ifndef uint
#  define uint  unsigned int
#endif
#ifndef uchar
#  define uchar unsigned char
#endif


/*
 * Support for 32-bit and 64-bit MEX files
 */
#ifndef mwSize
#  define mwSize int
#endif
#ifndef mwIndex
#  define mwIndex int
#endif
#ifndef mwSignedIndex
#  define mwSignedIndex int
#endif


/*
 * Records for call profile.
 */
int* mexprofrecord_= NULL;


/*
 * Support routines for copying data into and out of the MEX stubs
 */

void* mxWrapGetP(const mxArray* a, const char* fmt, const char** e)
{
    void* p = 0;
    mxArray* ap;
    if (mxGetClassID(a) == mxDOUBLE_CLASS && 
        mxGetM(a)*mxGetN(a) == 1 && *mxGetPr(a) == 0)
        return p;
    if (mxIsChar(a)) {
        char pbuf[128];
        mxGetString(a, pbuf, sizeof(pbuf));
        sscanf(pbuf, fmt, &p);
    } 
#ifdef R2008OO
    else if (ap = mxGetProperty(a, 0, "mwptr")) {
        return mxWrapGetP(ap, fmt, e);
    }
#endif
    if (p == 0)
        *e = "Invalid pointer";
    return p;
}

mxArray* mxWrapCreateP(void* p, const char* fmt)
{
    if (p == 0) {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    } else {
        char pbuf[128];
        sprintf(pbuf, fmt, p);
        return mxCreateString(pbuf);
    }
}

mxArray* mxWrapStrncpy(const char* s)
{
    if (s) {
        return mxCreateString(s);
    } else {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    }
}

double mxWrapGetScalar(const mxArray* a, const char** e)
{
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS || mxGetM(a)*mxGetN(a) != 1) {
        *e = "Invalid scalar argument";
        return 0;
    }
    return *mxGetPr(a);
}

char* mxWrapGetString(const mxArray* a, const char** e)
{
    char* s;
    mwSize slen;
    if (!a || (!mxIsChar(a) && mxGetM(a)*mxGetN(a) > 0)) {
        *e = "Invalid string argument";
        return NULL;
    }
    slen = mxGetM(a)*mxGetN(a) + 1;
    s = (char*) mxMalloc(slen);
    if (mxGetM(a)*mxGetN(a) == 0)
        *s = 0;
    else
        mxGetString(a, s, slen);
    return s;
}


#define mxWrapGetArrayDef(func, T) \
T* func(const mxArray* a, const char** e)     \
{ \
    T* array; \
    mwSize arraylen; \
    mwIndex i; \
    T* p; \
    double* q; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    q = mxGetPr(a); \
    for (i = 0; i < arraylen; ++i) \
        *p++ = (T) (*q++); \
    return array; \
}


#define mxWrapCopyDef(func, T) \
void func(mxArray* a, const T* q, mwSize n) \
{ \
    mwIndex i; \
    double* p = mxGetPr(a); \
    for (i = 0; i < n; ++i) \
        *p++ = *q++; \
}


#define mxWrapReturnDef(func, T) \
mxArray* func(const T* q, mwSize m, mwSize n) \
{ \
    mwIndex i; \
    double* p; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxREAL); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxREAL); \
        p = mxGetPr(a); \
        for (i = 0; i < m*n; ++i) \
            *p++ = *q++; \
        return a; \
    } \
}


#define mxWrapGetScalarZDef(func, T, ZT, setz) \
void func(T* z, const mxArray* a) \
{ \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    setz(z, (ZT) *pr, (pi ? (ZT) *pi : (ZT) 0)); \
}


#define mxWrapGetArrayZDef(func, T, ZT, setz) \
T* func(const mxArray* a, const char** e) \
{ \
    T* array; \
    mwSize arraylen; \
    mwIndex i; \
    T* p; \
    double* qr; \
    double* qi; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    qr = mxGetPr(a); \
    qi = mxGetPi(a); \
    for (i = 0; i < arraylen; ++i) { \
        ZT val_qr = *qr++; \
        ZT val_qi = (qi ? (ZT) *qi++ : (ZT) 0); \
        setz(p, val_qr, val_qi); \
        ++p; \
    } \
    return array; \
}


#define mxWrapCopyZDef(func, T, real, imag) \
void func(mxArray* a, const T* q, mwSize n) \
{ \
    mwIndex i; \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    for (i = 0; i < n; ++i) { \
        *pr++ = real(*q); \
        *pi++ = imag(*q); \
        ++q; \
    } \
}


#define mxWrapReturnZDef(func, T, real, imag) \
mxArray* func(const T* q, mwSize m, mwSize n) \
{ \
    mwIndex i; \
    double* pr; \
    double* pi; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxCOMPLEX); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxCOMPLEX); \
        pr = mxGetPr(a); \
        pi = mxGetPi(a); \
        for (i = 0; i < m*n; ++i) { \
            *pr++ = real(*q); \
            *pi++ = imag(*q); \
            ++q; \
        } \
        return a; \
    } \
}

/* Array copier definitions */
mxWrapGetArrayDef(mxWrapGetArray_bool, bool)
mxWrapCopyDef    (mxWrapCopy_bool,     bool)
mxWrapReturnDef  (mxWrapReturn_bool,   bool)
mxWrapGetArrayDef(mxWrapGetArray_char, char)
mxWrapCopyDef    (mxWrapCopy_char,     char)
mxWrapReturnDef  (mxWrapReturn_char,   char)
mxWrapGetArrayDef(mxWrapGetArray_double, double)
mxWrapCopyDef    (mxWrapCopy_double,     double)
mxWrapReturnDef  (mxWrapReturn_double,   double)
mxWrapGetArrayDef(mxWrapGetArray_float, float)
mxWrapCopyDef    (mxWrapCopy_float,     float)
mxWrapReturnDef  (mxWrapReturn_float,   float)
mxWrapGetArrayDef(mxWrapGetArray_int, int)
mxWrapCopyDef    (mxWrapCopy_int,     int)
mxWrapReturnDef  (mxWrapReturn_int,   int)
mxWrapGetArrayDef(mxWrapGetArray_long, long)
mxWrapCopyDef    (mxWrapCopy_long,     long)
mxWrapReturnDef  (mxWrapReturn_long,   long)
mxWrapGetArrayDef(mxWrapGetArray_mwIndex, mwIndex)
mxWrapCopyDef    (mxWrapCopy_mwIndex,     mwIndex)
mxWrapReturnDef  (mxWrapReturn_mwIndex,   mwIndex)
mxWrapGetArrayDef(mxWrapGetArray_mwSignedIndex, mwSignedIndex)
mxWrapCopyDef    (mxWrapCopy_mwSignedIndex,     mwSignedIndex)
mxWrapReturnDef  (mxWrapReturn_mwSignedIndex,   mwSignedIndex)
mxWrapGetArrayDef(mxWrapGetArray_mwSize, mwSize)
mxWrapCopyDef    (mxWrapCopy_mwSize,     mwSize)
mxWrapReturnDef  (mxWrapReturn_mwSize,   mwSize)
mxWrapGetArrayDef(mxWrapGetArray_size_t, size_t)
mxWrapCopyDef    (mxWrapCopy_size_t,     size_t)
mxWrapReturnDef  (mxWrapReturn_size_t,   size_t)
mxWrapGetArrayDef(mxWrapGetArray_uchar, uchar)
mxWrapCopyDef    (mxWrapCopy_uchar,     uchar)
mxWrapReturnDef  (mxWrapReturn_uchar,   uchar)
mxWrapGetArrayDef(mxWrapGetArray_uint, uint)
mxWrapCopyDef    (mxWrapCopy_uint,     uint)
mxWrapReturnDef  (mxWrapReturn_uint,   uint)
mxWrapGetArrayDef(mxWrapGetArray_ulong, ulong)
mxWrapCopyDef    (mxWrapCopy_ulong,     ulong)
mxWrapReturnDef  (mxWrapReturn_ulong,   ulong)

#if defined(MWF77_CAPS)
#define MWF77_generategroupct GENERATEGROUPCT
#define MWF77_generategroupmatlab GENERATEGROUPMATLAB
#define MWF77_nearmat NEARMAT
#define MWF77_precorr PRECORR
#define MWF77_fmmS FMMS
#define MWF77_fmmD FMMD
#define MWF77_fmmDstar FMMDSTAR
#define MWF77_fmmDEsecond FMMDESECOND
#define MWF77_computeEprimary COMPUTEEPRIMARY
#elif defined(MWF77_UNDERSCORE1)
#define MWF77_generategroupct generategroupct_
#define MWF77_generategroupmatlab generategroupmatlab_
#define MWF77_nearmat nearmat_
#define MWF77_precorr precorr_
#define MWF77_fmmS fmms_
#define MWF77_fmmD fmmd_
#define MWF77_fmmDstar fmmdstar_
#define MWF77_fmmDEsecond fmmdesecond_
#define MWF77_computeEprimary computeeprimary_
#else /* f2c convention */
#define MWF77_generategroupct generategroupct_
#define MWF77_generategroupmatlab generategroupmatlab_
#define MWF77_nearmat nearmat_
#define MWF77_precorr precorr_
#define MWF77_fmmS fmms_
#define MWF77_fmmD fmmd_
#define MWF77_fmmDstar fmmdstar_
#define MWF77_fmmDEsecond fmmdesecond_
#define MWF77_computeEprimary computeeprimary_
#endif

#ifdef __cplusplus
extern "C" { /* Prevent C++ name mangling */
#endif

#ifndef MWF77_RETURN
#define MWF77_RETURN int
#endif

MWF77_RETURN MWF77_generategroupct(int*, int*, double*, int*, double*, int*);
MWF77_RETURN MWF77_generategroupmatlab(int*, int*, double*, int*, double*, int*, int*, int*);
MWF77_RETURN MWF77_nearmat(double*, int*, int*, int*, int*, int*, int*, double*, double*, double*, double*, double*, double*);
MWF77_RETURN MWF77_precorr(double*, int*, int*, int*, int*, int*, double*, double*, double*);
MWF77_RETURN MWF77_fmmS(double*, double*, double*, int*, double*);
MWF77_RETURN MWF77_fmmD(double*, double*, double*, double*, int*, double*);
MWF77_RETURN MWF77_fmmDstar(double*, double*, double*, double*, int*, double*);
MWF77_RETURN MWF77_fmmDEsecond(double*, double*, double*, double*, double*, int*, double*, int*, double*, double*);
MWF77_RETURN MWF77_computeEprimary(double*, double*, double*, int*, double*, int*, double*);

#ifdef __cplusplus
} /* end extern C */
#endif

/* ---- BEMlib.mw: 25 ----
 * int nf = countfaceslegacy(int nte, int[4, nte] te2p, double[nte] condu, inout int[1] np2);
 */
const char* stubids1_ = "o int = countfaceslegacy(i int, i int[xx], i double[x], io int[x])";

void mexStub1(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int*        in1_ =0; /* te2p       */
    double*     in2_ =0; /* condu      */
    int*        in3_ =0; /* np2        */
    int         out0_;   /* nf         */
    mwSize      dim4_;   /* 4          */
    mwSize      dim5_;   /* nte        */
    mwSize      dim6_;   /* nte        */
    mwSize      dim7_;   /* 1          */

    dim4_ = (mwSize) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    dim5_ = (mwSize) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    dim6_ = (mwSize) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);

    if (mxGetM(prhs[1]) != dim4_ ||
        mxGetN(prhs[1]) != dim5_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim6_) {
        mw_err_txt_ = "Bad argument size: condu";        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim7_) {
        mw_err_txt_ = "Bad argument size: np2";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[1]++;
    out0_ = countfaceslegacy(in0_, in1_, in2_, in3_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim7_, 1, mxREAL);
    mxWrapCopy_int(plhs[1], in3_, dim7_);

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (in3_)  mxFree(in3_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- BEMlib.mw: 29 ----
 * makeBEMmeshlegacy(int nte, int[4, nte] te2p, double[3, np] p, double[nte] condu, inout int[3, nf] t2p, inout double[3, np2] p2, inout double[nf] epseff);
 */
const char* stubids2_ = "makeBEMmeshlegacy(i int, i int[xx], i double[xx], i double[x], io int[xx], io double[xx], io double[x])";

void mexStub2(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int*        in1_ =0; /* te2p       */
    double*     in2_ =0; /* p          */
    double*     in3_ =0; /* condu      */
    int*        in4_ =0; /* t2p        */
    double*     in5_ =0; /* p2         */
    double*     in6_ =0; /* epseff     */
    mwSize      dim7_;   /* 4          */
    mwSize      dim8_;   /* nte        */
    mwSize      dim9_;   /* 3          */
    mwSize      dim10_;   /* np         */
    mwSize      dim11_;   /* nte        */
    mwSize      dim12_;   /* 3          */
    mwSize      dim13_;   /* nf         */
    mwSize      dim14_;   /* 3          */
    mwSize      dim15_;   /* np2        */
    mwSize      dim16_;   /* nf         */

    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (mwSize) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (mwSize) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (mwSize) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (mwSize) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (mwSize) mxWrapGetScalar(prhs[16], &mw_err_txt_);

    if (mxGetM(prhs[1]) != dim7_ ||
        mxGetN(prhs[1]) != dim8_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim9_ ||
        mxGetN(prhs[2]) != dim10_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim11_) {
        mw_err_txt_ = "Bad argument size: condu";        goto mw_err_label;
    }

    if (mxGetM(prhs[4]) != dim12_ ||
        mxGetN(prhs[4]) != dim13_) {
        mw_err_txt_ = "Bad argument size: t2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim14_ ||
        mxGetN(prhs[5]) != dim15_) {
        mw_err_txt_ = "Bad argument size: p2";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != dim16_) {
        mw_err_txt_ = "Bad argument size: epseff";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_int(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_double(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_double(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[2]++;
    makeBEMmeshlegacy(in0_, in1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, dim13_, mxREAL);
    mxWrapCopy_int(plhs[0], in4_, dim12_*dim13_);
    plhs[1] = mxCreateDoubleMatrix(dim14_, dim15_, mxREAL);
    mxWrapCopy_double(plhs[1], in5_, dim14_*dim15_);
    plhs[2] = mxCreateDoubleMatrix(dim16_, 1, mxREAL);
    mxWrapCopy_double(plhs[2], in6_, dim16_);

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (in4_)  mxFree(in4_);
    if (in5_)  mxFree(in5_);
    if (in6_)  mxFree(in6_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- BEMlib.mw: 46 ----
 * int nf = countfaces(int nte, int[4, nte] te2p, int[nte] regid, inout int[1] np2);
 */
const char* stubids3_ = "o int = countfaces(i int, i int[xx], i int[x], io int[x])";

void mexStub3(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int*        in1_ =0; /* te2p       */
    int*        in2_ =0; /* regid      */
    int*        in3_ =0; /* np2        */
    int         out0_;   /* nf         */
    mwSize      dim4_;   /* 4          */
    mwSize      dim5_;   /* nte        */
    mwSize      dim6_;   /* nte        */
    mwSize      dim7_;   /* 1          */

    dim4_ = (mwSize) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    dim5_ = (mwSize) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    dim6_ = (mwSize) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);

    if (mxGetM(prhs[1]) != dim4_ ||
        mxGetN(prhs[1]) != dim5_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim6_) {
        mw_err_txt_ = "Bad argument size: regid";        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim7_) {
        mw_err_txt_ = "Bad argument size: np2";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[3]++;
    out0_ = countfaces(in0_, in1_, in2_, in3_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim7_, 1, mxREAL);
    mxWrapCopy_int(plhs[1], in3_, dim7_);

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (in2_)  mxFree(in2_);
    if (in3_)  mxFree(in3_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- BEMlib.mw: 54 ----
 * makeBEMmesh(int nte, int[4, nte] te2p, double[3, np] p, double[nreg] condu, int[nte] regid, inout int[3, nf] t2p, inout double[3, np2] p2, inout double[nf] sigdiff, inout double[nf] sigav, inout double[nf] rhotoIm);
 */
const char* stubids4_ = "makeBEMmesh(i int, i int[xx], i double[xx], i double[x], i int[x], io int[xx], io double[xx], io double[x], io double[x], io double[x])";

void mexStub4(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int         in0_;    /* nte        */
    int*        in1_ =0; /* te2p       */
    double*     in2_ =0; /* p          */
    double*     in3_ =0; /* condu      */
    int*        in4_ =0; /* regid      */
    int*        in5_ =0; /* t2p        */
    double*     in6_ =0; /* p2         */
    double*     in7_ =0; /* sigdiff    */
    double*     in8_ =0; /* sigav      */
    double*     in9_ =0; /* rhotoIm    */
    mwSize      dim10_;   /* 4          */
    mwSize      dim11_;   /* nte        */
    mwSize      dim12_;   /* 3          */
    mwSize      dim13_;   /* np         */
    mwSize      dim14_;   /* nreg       */
    mwSize      dim15_;   /* nte        */
    mwSize      dim16_;   /* 3          */
    mwSize      dim17_;   /* nf         */
    mwSize      dim18_;   /* 3          */
    mwSize      dim19_;   /* np2        */
    mwSize      dim20_;   /* nf         */
    mwSize      dim21_;   /* nf         */
    mwSize      dim22_;   /* nf         */

    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (mwSize) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (mwSize) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (mwSize) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (mwSize) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (mwSize) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (mwSize) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (mwSize) mxWrapGetScalar(prhs[19], &mw_err_txt_);
    dim20_ = (mwSize) mxWrapGetScalar(prhs[20], &mw_err_txt_);
    dim21_ = (mwSize) mxWrapGetScalar(prhs[21], &mw_err_txt_);
    dim22_ = (mwSize) mxWrapGetScalar(prhs[22], &mw_err_txt_);

    if (mxGetM(prhs[1]) != dim10_ ||
        mxGetN(prhs[1]) != dim11_) {
        mw_err_txt_ = "Bad argument size: te2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim12_ ||
        mxGetN(prhs[2]) != dim13_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim14_) {
        mw_err_txt_ = "Bad argument size: condu";        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim15_) {
        mw_err_txt_ = "Bad argument size: regid";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim16_ ||
        mxGetN(prhs[5]) != dim17_) {
        mw_err_txt_ = "Bad argument size: t2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim18_ ||
        mxGetN(prhs[6]) != dim19_) {
        mw_err_txt_ = "Bad argument size: p2";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != dim20_) {
        mw_err_txt_ = "Bad argument size: sigdiff";        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim21_) {
        mw_err_txt_ = "Bad argument size: sigav";        goto mw_err_label;
    }

    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != dim22_) {
        mw_err_txt_ = "Bad argument size: rhotoIm";        goto mw_err_label;
    }

    in0_ = (int) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_int(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_double(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxWrapGetArray_double(prhs[7], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_double(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;
    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != 0) {
        in9_ = mxWrapGetArray_double(prhs[9], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in9_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[4]++;
    makeBEMmesh(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_);
    plhs[0] = mxCreateDoubleMatrix(dim16_, dim17_, mxREAL);
    mxWrapCopy_int(plhs[0], in5_, dim16_*dim17_);
    plhs[1] = mxCreateDoubleMatrix(dim18_, dim19_, mxREAL);
    mxWrapCopy_double(plhs[1], in6_, dim18_*dim19_);
    plhs[2] = mxCreateDoubleMatrix(dim20_, 1, mxREAL);
    mxWrapCopy_double(plhs[2], in7_, dim20_);
    plhs[3] = mxCreateDoubleMatrix(dim21_, 1, mxREAL);
    mxWrapCopy_double(plhs[3], in8_, dim21_);
    plhs[4] = mxCreateDoubleMatrix(dim22_, 1, mxREAL);
    mxWrapCopy_double(plhs[4], in9_, dim22_);

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (in4_)  mxFree(in4_);
    if (in5_)  mxFree(in5_);
    if (in6_)  mxFree(in6_);
    if (in7_)  mxFree(in7_);
    if (in8_)  mxFree(in8_);
    if (in9_)  mxFree(in9_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- BEMlib.mw: 108 ----
 * generategroupct(int[3, nt] t2p, int[1] nt, double[3, np] p, int[1] np, double[1] del, output int[1] ncol);
 */
const char* stubids5_ = "generategroupct(i int[xx], i int[x], i double[xx], i int[x], i double[x], o int[x])";

void mexStub5(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* t2p        */
    int*        in1_ =0; /* nt         */
    double*     in2_ =0; /* p          */
    int*        in3_ =0; /* np         */
    double*     in4_ =0; /* del        */
    int*        out0_=0; /* ncol       */
    mwSize      dim5_;   /* 3          */
    mwSize      dim6_;   /* nt         */
    mwSize      dim7_;   /* 1          */
    mwSize      dim8_;   /* 3          */
    mwSize      dim9_;   /* np         */
    mwSize      dim10_;   /* 1          */
    mwSize      dim11_;   /* 1          */
    mwSize      dim12_;   /* 1          */

    dim5_ = (mwSize) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    dim6_ = (mwSize) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (mwSize) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim5_ ||
        mxGetN(prhs[0]) != dim6_) {
        mw_err_txt_ = "Bad argument size: t2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim7_) {
        mw_err_txt_ = "Bad argument size: nt";        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim8_ ||
        mxGetN(prhs[2]) != dim9_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: np";        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim11_) {
        mw_err_txt_ = "Bad argument size: del";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    out0_ = (int*) mxMalloc(dim12_*sizeof(int));
    if (mexprofrecord_)
        mexprofrecord_[5]++;
    MWF77_generategroupct(in0_, in1_, in2_, in3_, in4_, out0_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, 1, mxREAL);
    mxWrapCopy_int(plhs[0], out0_, dim12_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in3_)  mxFree(in3_);
    if (out0_) mxFree(out0_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- BEMlib.mw: 109 ----
 * generategroupmatlab(int[3, nt] t2p, int[1] nt, double[3, np] p, int[1] np, double[1] del, output int[ncol] col, output int[ncol] row, int[1] ncol);
 */
const char* stubids6_ = "generategroupmatlab(i int[xx], i int[x], i double[xx], i int[x], i double[x], o int[x], o int[x], i int[x])";

void mexStub6(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* t2p        */
    int*        in1_ =0; /* nt         */
    double*     in2_ =0; /* p          */
    int*        in3_ =0; /* np         */
    double*     in4_ =0; /* del        */
    int*        in5_ =0; /* ncol       */
    int*        out0_=0; /* col        */
    int*        out1_=0; /* row        */
    mwSize      dim6_;   /* 3          */
    mwSize      dim7_;   /* nt         */
    mwSize      dim8_;   /* 1          */
    mwSize      dim9_;   /* 3          */
    mwSize      dim10_;   /* np         */
    mwSize      dim11_;   /* 1          */
    mwSize      dim12_;   /* 1          */
    mwSize      dim13_;   /* ncol       */
    mwSize      dim14_;   /* ncol       */
    mwSize      dim15_;   /* 1          */

    dim6_ = (mwSize) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (mwSize) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (mwSize) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (mwSize) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (mwSize) mxWrapGetScalar(prhs[15], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim6_ ||
        mxGetN(prhs[0]) != dim7_) {
        mw_err_txt_ = "Bad argument size: t2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim8_) {
        mw_err_txt_ = "Bad argument size: nt";        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim9_ ||
        mxGetN(prhs[2]) != dim10_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim11_) {
        mw_err_txt_ = "Bad argument size: np";        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim12_) {
        mw_err_txt_ = "Bad argument size: del";        goto mw_err_label;
    }

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != dim15_) {
        mw_err_txt_ = "Bad argument size: ncol";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    out0_ = (int*) mxMalloc(dim13_*sizeof(int));
    out1_ = (int*) mxMalloc(dim14_*sizeof(int));
    if (mexprofrecord_)
        mexprofrecord_[6]++;
    MWF77_generategroupmatlab(in0_, in1_, in2_, in3_, in4_, out0_, out1_, in5_);
    plhs[0] = mxCreateDoubleMatrix(dim13_, 1, mxREAL);
    mxWrapCopy_int(plhs[0], out0_, dim13_);
    plhs[1] = mxCreateDoubleMatrix(dim14_, 1, mxREAL);
    mxWrapCopy_int(plhs[1], out1_, dim14_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in3_)  mxFree(in3_);
    if (out0_) mxFree(out0_);
    if (out1_) mxFree(out1_);
    if (in5_)  mxFree(in5_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- BEMlib.mw: 125 ----
 * nearmat(double[3, np] p, int[1] np, int[3, nt] t2p, int[1] nt, int[ncols] row, int[ncols] col, int[1] ncols, double[3, nt] normal, double[nt] area, output double[ncols] Dstar0, output double[ncols] S0, output double[ncols, 9] D1, output double[ncols, 9] S1);
 * Also at BEMlib.mw: 167
 */
const char* stubids7_ = "nearmat(i double[xx], i int[x], i int[xx], i int[x], i int[x], i int[x], i int[x], i double[xx], i double[x], o double[x], o double[x], o double[xx], o double[xx])";

void mexStub7(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* p          */
    int*        in1_ =0; /* np         */
    int*        in2_ =0; /* t2p        */
    int*        in3_ =0; /* nt         */
    int*        in4_ =0; /* row        */
    int*        in5_ =0; /* col        */
    int*        in6_ =0; /* ncols      */
    double*     in7_ =0; /* normal     */
    double*     in8_ =0; /* area       */
    double*     out0_=0; /* Dstar0     */
    double*     out1_=0; /* S0         */
    double*     out2_=0; /* D1         */
    double*     out3_=0; /* S1         */
    mwSize      dim9_;   /* 3          */
    mwSize      dim10_;   /* np         */
    mwSize      dim11_;   /* 1          */
    mwSize      dim12_;   /* 3          */
    mwSize      dim13_;   /* nt         */
    mwSize      dim14_;   /* 1          */
    mwSize      dim15_;   /* ncols      */
    mwSize      dim16_;   /* ncols      */
    mwSize      dim17_;   /* 1          */
    mwSize      dim18_;   /* 3          */
    mwSize      dim19_;   /* nt         */
    mwSize      dim20_;   /* nt         */
    mwSize      dim21_;   /* ncols      */
    mwSize      dim22_;   /* ncols      */
    mwSize      dim23_;   /* ncols      */
    mwSize      dim24_;   /* 9          */
    mwSize      dim25_;   /* ncols      */
    mwSize      dim26_;   /* 9          */

    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (mwSize) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (mwSize) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (mwSize) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (mwSize) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (mwSize) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (mwSize) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (mwSize) mxWrapGetScalar(prhs[19], &mw_err_txt_);
    dim20_ = (mwSize) mxWrapGetScalar(prhs[20], &mw_err_txt_);
    dim21_ = (mwSize) mxWrapGetScalar(prhs[21], &mw_err_txt_);
    dim22_ = (mwSize) mxWrapGetScalar(prhs[22], &mw_err_txt_);
    dim23_ = (mwSize) mxWrapGetScalar(prhs[23], &mw_err_txt_);
    dim24_ = (mwSize) mxWrapGetScalar(prhs[24], &mw_err_txt_);
    dim25_ = (mwSize) mxWrapGetScalar(prhs[25], &mw_err_txt_);
    dim26_ = (mwSize) mxWrapGetScalar(prhs[26], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim9_ ||
        mxGetN(prhs[0]) != dim10_) {
        mw_err_txt_ = "Bad argument size: p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim11_) {
        mw_err_txt_ = "Bad argument size: np";        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim12_ ||
        mxGetN(prhs[2]) != dim13_) {
        mw_err_txt_ = "Bad argument size: t2p";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim14_) {
        mw_err_txt_ = "Bad argument size: nt";        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim15_) {
        mw_err_txt_ = "Bad argument size: row";        goto mw_err_label;
    }

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != dim16_) {
        mw_err_txt_ = "Bad argument size: col";        goto mw_err_label;
    }

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != dim17_) {
        mw_err_txt_ = "Bad argument size: ncols";        goto mw_err_label;
    }

    if (mxGetM(prhs[7]) != dim18_ ||
        mxGetN(prhs[7]) != dim19_) {
        mw_err_txt_ = "Bad argument size: normal";
        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim20_) {
        mw_err_txt_ = "Bad argument size: area";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_int(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_int(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxGetPr(prhs[8]);
    } else
        in8_ = NULL;
    out0_ = (double*) mxMalloc(dim21_*sizeof(double));
    out1_ = (double*) mxMalloc(dim22_*sizeof(double));
    out2_ = (double*) mxMalloc(dim23_*dim24_*sizeof(double));
    out3_ = (double*) mxMalloc(dim25_*dim26_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[7]++;
    MWF77_nearmat(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, out0_, out1_, out2_, out3_);
    plhs[0] = mxCreateDoubleMatrix(dim21_, 1, mxREAL);
    mxWrapCopy_double(plhs[0], out0_, dim21_);
    plhs[1] = mxCreateDoubleMatrix(dim22_, 1, mxREAL);
    mxWrapCopy_double(plhs[1], out1_, dim22_);
    plhs[2] = mxCreateDoubleMatrix(dim23_, dim24_, mxREAL);
    mxWrapCopy_double(plhs[2], out2_, dim23_*dim24_);
    plhs[3] = mxCreateDoubleMatrix(dim25_, dim26_, mxREAL);
    mxWrapCopy_double(plhs[3], out3_, dim25_*dim26_);

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (in2_)  mxFree(in2_);
    if (in3_)  mxFree(in3_);
    if (in4_)  mxFree(in4_);
    if (in5_)  mxFree(in5_);
    if (in6_)  mxFree(in6_);
    if (out0_) mxFree(out0_);
    if (out1_) mxFree(out1_);
    if (out2_) mxFree(out2_);
    if (out3_) mxFree(out3_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- BEMlib.mw: 240 ----
 * precorr(double[3, nfmm] rfmm, int[1] nt, int[1] nquad, int[ncols] row, int[ncols] col, int[1] ncols, double[3, nt] normal, output double[ncols, nquad2] S0, output double[ncols, nquad2] D0);
 */
const char* stubids9_ = "precorr(i double[xx], i int[x], i int[x], i int[x], i int[x], i int[x], i double[xx], o double[xx], o double[xx])";

void mexStub9(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* rfmm       */
    int*        in1_ =0; /* nt         */
    int*        in2_ =0; /* nquad      */
    int*        in3_ =0; /* row        */
    int*        in4_ =0; /* col        */
    int*        in5_ =0; /* ncols      */
    double*     in6_ =0; /* normal     */
    double*     out0_=0; /* S0         */
    double*     out1_=0; /* D0         */
    mwSize      dim7_;   /* 3          */
    mwSize      dim8_;   /* nfmm       */
    mwSize      dim9_;   /* 1          */
    mwSize      dim10_;   /* 1          */
    mwSize      dim11_;   /* ncols      */
    mwSize      dim12_;   /* ncols      */
    mwSize      dim13_;   /* 1          */
    mwSize      dim14_;   /* 3          */
    mwSize      dim15_;   /* nt         */
    mwSize      dim16_;   /* ncols      */
    mwSize      dim17_;   /* nquad2     */
    mwSize      dim18_;   /* ncols      */
    mwSize      dim19_;   /* nquad2     */

    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (mwSize) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (mwSize) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (mwSize) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (mwSize) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (mwSize) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (mwSize) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (mwSize) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (mwSize) mxWrapGetScalar(prhs[19], &mw_err_txt_);

    if (mxGetM(prhs[0]) != dim7_ ||
        mxGetN(prhs[0]) != dim8_) {
        mw_err_txt_ = "Bad argument size: rfmm";
        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim9_) {
        mw_err_txt_ = "Bad argument size: nt";        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim10_) {
        mw_err_txt_ = "Bad argument size: nquad";        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim11_) {
        mw_err_txt_ = "Bad argument size: row";        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim12_) {
        mw_err_txt_ = "Bad argument size: col";        goto mw_err_label;
    }

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != dim13_) {
        mw_err_txt_ = "Bad argument size: ncols";        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim14_ ||
        mxGetN(prhs[6]) != dim15_) {
        mw_err_txt_ = "Bad argument size: normal";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_int(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    out0_ = (double*) mxMalloc(dim16_*dim17_*sizeof(double));
    out1_ = (double*) mxMalloc(dim18_*dim19_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[9]++;
    MWF77_precorr(in0_, in1_, in2_, in3_, in4_, in5_, in6_, out0_, out1_);
    plhs[0] = mxCreateDoubleMatrix(dim16_, dim17_, mxREAL);
    mxWrapCopy_double(plhs[0], out0_, dim16_*dim17_);
    plhs[1] = mxCreateDoubleMatrix(dim18_, dim19_, mxREAL);
    mxWrapCopy_double(plhs[1], out1_, dim18_*dim19_);

mw_err_label:
    if (in1_)  mxFree(in1_);
    if (in2_)  mxFree(in2_);
    if (in3_)  mxFree(in3_);
    if (in4_)  mxFree(in4_);
    if (in5_)  mxFree(in5_);
    if (out0_) mxFree(out0_);
    if (out1_) mxFree(out1_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- BEMlib.mw: 252 ----
 * fmmS(double[1] errfmm, double[nfmm] ytemp, double[3, nfmm] rfmm, int[1] nfmm, output double[nfmm] ytemp);
 */
const char* stubids10_ = "fmmS(i double[x], i double[x], i double[xx], i int[x], o double[x])";

void mexStub10(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* errfmm     */
    double*     in1_ =0; /* ytemp      */
    double*     in2_ =0; /* rfmm       */
    int*        in3_ =0; /* nfmm       */
    double*     out0_=0; /* ytemp      */
    mwSize      dim4_;   /* 1          */
    mwSize      dim5_;   /* nfmm       */
    mwSize      dim6_;   /* 3          */
    mwSize      dim7_;   /* nfmm       */
    mwSize      dim8_;   /* 1          */
    mwSize      dim9_;   /* nfmm       */

    dim4_ = (mwSize) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    dim5_ = (mwSize) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    dim6_ = (mwSize) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (mwSize) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim4_) {
        mw_err_txt_ = "Bad argument size: errfmm";        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim5_) {
        mw_err_txt_ = "Bad argument size: ytemp";        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim6_ ||
        mxGetN(prhs[2]) != dim7_) {
        mw_err_txt_ = "Bad argument size: rfmm";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim8_) {
        mw_err_txt_ = "Bad argument size: nfmm";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    out0_ = (double*) mxMalloc(dim9_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[10]++;
    MWF77_fmmS(in0_, in1_, in2_, in3_, out0_);
    plhs[0] = mxCreateDoubleMatrix(dim9_, 1, mxREAL);
    mxWrapCopy_double(plhs[0], out0_, dim9_);

mw_err_label:
    if (in3_)  mxFree(in3_);
    if (out0_) mxFree(out0_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- BEMlib.mw: 260 ----
 * fmmD(double[1] errfmm, double[nfmm] ytemp, double[3, nfmm] rfmm, double[3, nfmm] nhatfmm, int[1] nfmm, output double[nfmm] ytemp);
 * Also at BEMlib.mw: 276
 */
const char* stubids11_ = "fmmD(i double[x], i double[x], i double[xx], i double[xx], i int[x], o double[x])";

void mexStub11(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* errfmm     */
    double*     in1_ =0; /* ytemp      */
    double*     in2_ =0; /* rfmm       */
    double*     in3_ =0; /* nhatfmm    */
    int*        in4_ =0; /* nfmm       */
    double*     out0_=0; /* ytemp      */
    mwSize      dim5_;   /* 1          */
    mwSize      dim6_;   /* nfmm       */
    mwSize      dim7_;   /* 3          */
    mwSize      dim8_;   /* nfmm       */
    mwSize      dim9_;   /* 3          */
    mwSize      dim10_;   /* nfmm       */
    mwSize      dim11_;   /* 1          */
    mwSize      dim12_;   /* nfmm       */

    dim5_ = (mwSize) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    dim6_ = (mwSize) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (mwSize) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim5_) {
        mw_err_txt_ = "Bad argument size: errfmm";        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim6_) {
        mw_err_txt_ = "Bad argument size: ytemp";        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim7_ ||
        mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: rfmm";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim9_ ||
        mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: nhatfmm";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim11_) {
        mw_err_txt_ = "Bad argument size: nfmm";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_int(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    out0_ = (double*) mxMalloc(dim12_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[11]++;
    MWF77_fmmD(in0_, in1_, in2_, in3_, in4_, out0_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, 1, mxREAL);
    mxWrapCopy_double(plhs[0], out0_, dim12_);

mw_err_label:
    if (in4_)  mxFree(in4_);
    if (out0_) mxFree(out0_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- BEMlib.mw: 266 ----
 * fmmDstar(double[1] errfmm, double[nfmm] ytemp, double[3, nfmm] rfmm, double[3, nfmm] nhatfmm, int[1] nfmm, output double[nfmm] ytemp);
 * Also at BEMlib.mw: 286
 */
const char* stubids12_ = "fmmDstar(i double[x], i double[x], i double[xx], i double[xx], i int[x], o double[x])";

void mexStub12(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* errfmm     */
    double*     in1_ =0; /* ytemp      */
    double*     in2_ =0; /* rfmm       */
    double*     in3_ =0; /* nhatfmm    */
    int*        in4_ =0; /* nfmm       */
    double*     out0_=0; /* ytemp      */
    mwSize      dim5_;   /* 1          */
    mwSize      dim6_;   /* nfmm       */
    mwSize      dim7_;   /* 3          */
    mwSize      dim8_;   /* nfmm       */
    mwSize      dim9_;   /* 3          */
    mwSize      dim10_;   /* nfmm       */
    mwSize      dim11_;   /* 1          */
    mwSize      dim12_;   /* nfmm       */

    dim5_ = (mwSize) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    dim6_ = (mwSize) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (mwSize) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim5_) {
        mw_err_txt_ = "Bad argument size: errfmm";        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim6_) {
        mw_err_txt_ = "Bad argument size: ytemp";        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim7_ ||
        mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: rfmm";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim9_ ||
        mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: nhatfmm";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim11_) {
        mw_err_txt_ = "Bad argument size: nfmm";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_int(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    out0_ = (double*) mxMalloc(dim12_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[12]++;
    MWF77_fmmDstar(in0_, in1_, in2_, in3_, in4_, out0_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, 1, mxREAL);
    mxWrapCopy_double(plhs[0], out0_, dim12_);

mw_err_label:
    if (in4_)  mxFree(in4_);
    if (out0_) mxFree(out0_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- BEMlib.mw: 295 ----
 * fmmDEsecond(double[1] errfmm, double[nfmm] Vfmm, double[nfmm] Efmm, double[3, nfmm] rfmm, double[3, nfmm] nhatfmm, int[1] nfmm, double[3, nobs] robs, int[1] nobs, output double[nobs] pot, output double[3, nobs] fld);
 */
const char* stubids15_ = "fmmDEsecond(i double[x], i double[x], i double[x], i double[xx], i double[xx], i int[x], i double[xx], i int[x], o double[x], o double[xx])";

void mexStub15(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* errfmm     */
    double*     in1_ =0; /* Vfmm       */
    double*     in2_ =0; /* Efmm       */
    double*     in3_ =0; /* rfmm       */
    double*     in4_ =0; /* nhatfmm    */
    int*        in5_ =0; /* nfmm       */
    double*     in6_ =0; /* robs       */
    int*        in7_ =0; /* nobs       */
    double*     out0_=0; /* pot        */
    double*     out1_=0; /* fld        */
    mwSize      dim8_;   /* 1          */
    mwSize      dim9_;   /* nfmm       */
    mwSize      dim10_;   /* nfmm       */
    mwSize      dim11_;   /* 3          */
    mwSize      dim12_;   /* nfmm       */
    mwSize      dim13_;   /* 3          */
    mwSize      dim14_;   /* nfmm       */
    mwSize      dim15_;   /* 1          */
    mwSize      dim16_;   /* 3          */
    mwSize      dim17_;   /* nobs       */
    mwSize      dim18_;   /* 1          */
    mwSize      dim19_;   /* nobs       */
    mwSize      dim20_;   /* 3          */
    mwSize      dim21_;   /* nobs       */

    dim8_ = (mwSize) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (mwSize) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (mwSize) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (mwSize) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (mwSize) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (mwSize) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (mwSize) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (mwSize) mxWrapGetScalar(prhs[19], &mw_err_txt_);
    dim20_ = (mwSize) mxWrapGetScalar(prhs[20], &mw_err_txt_);
    dim21_ = (mwSize) mxWrapGetScalar(prhs[21], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim8_) {
        mw_err_txt_ = "Bad argument size: errfmm";        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim9_) {
        mw_err_txt_ = "Bad argument size: Vfmm";        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim10_) {
        mw_err_txt_ = "Bad argument size: Efmm";        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim11_ ||
        mxGetN(prhs[3]) != dim12_) {
        mw_err_txt_ = "Bad argument size: rfmm";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4]) != dim13_ ||
        mxGetN(prhs[4]) != dim14_) {
        mw_err_txt_ = "Bad argument size: nhatfmm";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != dim15_) {
        mw_err_txt_ = "Bad argument size: nfmm";        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim16_ ||
        mxGetN(prhs[6]) != dim17_) {
        mw_err_txt_ = "Bad argument size: robs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != dim18_) {
        mw_err_txt_ = "Bad argument size: nobs";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxWrapGetArray_int(prhs[7], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in7_ = NULL;
    out0_ = (double*) mxMalloc(dim19_*sizeof(double));
    out1_ = (double*) mxMalloc(dim20_*dim21_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[15]++;
    MWF77_fmmDEsecond(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, out0_, out1_);
    plhs[0] = mxCreateDoubleMatrix(dim19_, 1, mxREAL);
    mxWrapCopy_double(plhs[0], out0_, dim19_);
    plhs[1] = mxCreateDoubleMatrix(dim20_, dim21_, mxREAL);
    mxWrapCopy_double(plhs[1], out1_, dim20_*dim21_);

mw_err_label:
    if (in5_)  mxFree(in5_);
    if (in7_)  mxFree(in7_);
    if (out0_) mxFree(out0_);
    if (out1_) mxFree(out1_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- BEMlib.mw: 303 ----
 * computeEprimary(double[1] errfmm, double[3, ns] rs, double[3, ns] js, int[1] ns, double[3, nobs] robs, int[1] nobs, output double[3, nobs] Eprimary);
 */
const char* stubids16_ = "computeEprimary(i double[x], i double[xx], i double[xx], i int[x], i double[xx], i int[x], o double[xx])";

void mexStub16(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double*     in0_ =0; /* errfmm     */
    double*     in1_ =0; /* rs         */
    double*     in2_ =0; /* js         */
    int*        in3_ =0; /* ns         */
    double*     in4_ =0; /* robs       */
    int*        in5_ =0; /* nobs       */
    double*     out0_=0; /* Eprimary   */
    mwSize      dim6_;   /* 1          */
    mwSize      dim7_;   /* 3          */
    mwSize      dim8_;   /* ns         */
    mwSize      dim9_;   /* 3          */
    mwSize      dim10_;   /* ns         */
    mwSize      dim11_;   /* 1          */
    mwSize      dim12_;   /* 3          */
    mwSize      dim13_;   /* nobs       */
    mwSize      dim14_;   /* 1          */
    mwSize      dim15_;   /* 3          */
    mwSize      dim16_;   /* nobs       */

    dim6_ = (mwSize) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (mwSize) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (mwSize) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (mwSize) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (mwSize) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (mwSize) mxWrapGetScalar(prhs[16], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim6_) {
        mw_err_txt_ = "Bad argument size: errfmm";        goto mw_err_label;
    }

    if (mxGetM(prhs[1]) != dim7_ ||
        mxGetN(prhs[1]) != dim8_) {
        mw_err_txt_ = "Bad argument size: rs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2]) != dim9_ ||
        mxGetN(prhs[2]) != dim10_) {
        mw_err_txt_ = "Bad argument size: js";
        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim11_) {
        mw_err_txt_ = "Bad argument size: ns";        goto mw_err_label;
    }

    if (mxGetM(prhs[4]) != dim12_ ||
        mxGetN(prhs[4]) != dim13_) {
        mw_err_txt_ = "Bad argument size: robs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != dim14_) {
        mw_err_txt_ = "Bad argument size: nobs";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxGetPr(prhs[0]);
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxGetPr(prhs[4]);
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_int(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    out0_ = (double*) mxMalloc(dim15_*dim16_*sizeof(double));
    if (mexprofrecord_)
        mexprofrecord_[16]++;
    MWF77_computeEprimary(in0_, in1_, in2_, in3_, in4_, in5_, out0_);
    plhs[0] = mxCreateDoubleMatrix(dim15_, dim16_, mxREAL);
    mxWrapCopy_double(plhs[0], out0_, dim15_*dim16_);

mw_err_label:
    if (in3_)  mxFree(in3_);
    if (in5_)  mxFree(in5_);
    if (out0_) mxFree(out0_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ----
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[])
{
    char id[512];
    if (nrhs == 0) {
        mexPrintf("Mex function installed\n");
        return;
    }

    if (mxGetString(prhs[0], id, sizeof(id)) != 0)
        mexErrMsgTxt("Identifier should be a string");
    else if (strcmp(id, stubids1_) == 0)
        mexStub1(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids2_) == 0)
        mexStub2(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids3_) == 0)
        mexStub3(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids4_) == 0)
        mexStub4(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids5_) == 0)
        mexStub5(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids6_) == 0)
        mexStub6(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids7_) == 0)
        mexStub7(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids9_) == 0)
        mexStub9(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids10_) == 0)
        mexStub10(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids11_) == 0)
        mexStub11(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids12_) == 0)
        mexStub12(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids15_) == 0)
        mexStub15(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids16_) == 0)
        mexStub16(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, "*profile on*") == 0) {
        if (!mexprofrecord_) {
            mexprofrecord_ = (int*) malloc(17 * sizeof(int));
            mexLock();
        }
        memset(mexprofrecord_, 0, 17 * sizeof(int));
    } else if (strcmp(id, "*profile off*") == 0) {
        if (mexprofrecord_) {
            free(mexprofrecord_);
            mexUnlock();
        }
        mexprofrecord_ = NULL;
    } else if (strcmp(id, "*profile report*") == 0) {
        if (!mexprofrecord_)
            mexPrintf("Profiler inactive\n");
        mexPrintf("%d calls to BEMlib.mw:25\n", mexprofrecord_[1]);
        mexPrintf("%d calls to BEMlib.mw:29\n", mexprofrecord_[2]);
        mexPrintf("%d calls to BEMlib.mw:46\n", mexprofrecord_[3]);
        mexPrintf("%d calls to BEMlib.mw:54\n", mexprofrecord_[4]);
        mexPrintf("%d calls to BEMlib.mw:108\n", mexprofrecord_[5]);
        mexPrintf("%d calls to BEMlib.mw:109\n", mexprofrecord_[6]);
        mexPrintf("%d calls to BEMlib.mw:125 (BEMlib.mw:167)\n", mexprofrecord_[7]);
        mexPrintf("%d calls to BEMlib.mw:240\n", mexprofrecord_[9]);
        mexPrintf("%d calls to BEMlib.mw:252\n", mexprofrecord_[10]);
        mexPrintf("%d calls to BEMlib.mw:260 (BEMlib.mw:276)\n", mexprofrecord_[11]);
        mexPrintf("%d calls to BEMlib.mw:266 (BEMlib.mw:286)\n", mexprofrecord_[12]);
        mexPrintf("%d calls to BEMlib.mw:295\n", mexprofrecord_[15]);
        mexPrintf("%d calls to BEMlib.mw:303\n", mexprofrecord_[16]);
    } else if (strcmp(id, "*profile log*") == 0) {
        FILE* logfp;
        if (nrhs != 2 || mxGetString(prhs[1], id, sizeof(id)) != 0)
            mexErrMsgTxt("Must have two string arguments");
        logfp = fopen(id, "w+");
        if (!logfp)
            mexErrMsgTxt("Cannot open log for output");
        if (!mexprofrecord_)
            fprintf(logfp, "Profiler inactive\n");
        fprintf(logfp, "%d calls to BEMlib.mw:25\n", mexprofrecord_[1]);
        fprintf(logfp, "%d calls to BEMlib.mw:29\n", mexprofrecord_[2]);
        fprintf(logfp, "%d calls to BEMlib.mw:46\n", mexprofrecord_[3]);
        fprintf(logfp, "%d calls to BEMlib.mw:54\n", mexprofrecord_[4]);
        fprintf(logfp, "%d calls to BEMlib.mw:108\n", mexprofrecord_[5]);
        fprintf(logfp, "%d calls to BEMlib.mw:109\n", mexprofrecord_[6]);
        fprintf(logfp, "%d calls to BEMlib.mw:125 (BEMlib.mw:167)\n", mexprofrecord_[7]);
        fprintf(logfp, "%d calls to BEMlib.mw:240\n", mexprofrecord_[9]);
        fprintf(logfp, "%d calls to BEMlib.mw:252\n", mexprofrecord_[10]);
        fprintf(logfp, "%d calls to BEMlib.mw:260 (BEMlib.mw:276)\n", mexprofrecord_[11]);
        fprintf(logfp, "%d calls to BEMlib.mw:266 (BEMlib.mw:286)\n", mexprofrecord_[12]);
        fprintf(logfp, "%d calls to BEMlib.mw:295\n", mexprofrecord_[15]);
        fprintf(logfp, "%d calls to BEMlib.mw:303\n", mexprofrecord_[16]);
        fclose(logfp);
    } else
        mexErrMsgTxt("Unknown identifier");
}

